add significant kmer check after removing overlap
.eps file BoundingBox size will become unrealistic if no significant kmers is left after removing kmers overlapping with fixed positions. This leads to convert errors:

    Unrecoverable error: rangecheck in .putdeviceprops
    Unrecoverable error: rangecheck in .putdeviceprops
    convert: no images defined `kpLogo.most.significant.each.position.png' @ error/convert.c/ConvertImageCommand/3300.
    Error: /limitcheck in --token--

.eps file head:

    %%BoundingBox:   0  0  1755.000000 1428285685708570235040932615236658626050357399547651174626792726651792037379231059021673775872035782656.000000 
    %%Pages: 0                         
    %%DocumentFonts:                   
    %%EndComments

Thus, I suggest to add the significant kmer check code after line 1109 in kpLogo.cpp (which invokes remove_kmers_overlapping_with_fixed_positions()).